# Generated by Django 2.0.5 on 2018-08-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryByMinute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('open', models.IntegerField()),
                ('close', models.IntegerField()),
                ('volumefrom', models.IntegerField()),
                ('volumeto', models.IntegerField()),
                ('crypto', models.CharField(max_length=10)),
                ('curr', models.CharField(max_length=10)),
            ],
        ),
    ]
