# Generated by Django 2.0.5 on 2018-08-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crypto_net', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historybyminute',
            name='time',
            field=models.IntegerField(unique=True),
        ),
    ]
